"""Typed worker settings (pydantic-settings).

Fields map to environment variables with the ``TUTTITRIP_`` prefix; nested
models use ``__`` (``TUTTITRIP_LLM__LOCAL_MODEL``). Three fields read the names
the backend deploy writes into ``~/tuttitrip/envs/<env>.worker.env``
(``deploy/CONVENTIONS.md`` in the backend): ``TUTTITRIP_WORKER_DATABASE_URL``,
``DBOS_SYSTEM_DATABASE_URL`` and ``DBOS__APPVERSION``.
``.env.example`` must list exactly these variables (a test enforces it).
"""

from functools import lru_cache
from typing import Literal

from pydantic import BaseModel, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

ENV_PREFIX = "TUTTITRIP_"
ENV_NESTED_DELIMITER = "__"
LOCAL_ENVIRONMENT = "local"
LOCAL_DATABASE_URL = "postgresql://tuttitrip:tuttitrip@localhost:5432/tuttitrip"


class DbosSettings(BaseModel):
    """DBOS runtime options."""

    # Seconds `docker stop` gives running workflows before we exit; keep it
    # below the container stop timeout (the deploy uses --stop-timeout 40).
    shutdown_timeout_sec: int = Field(default=30, ge=0, le=600)
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"
    step_max_attempts: int = Field(
        default=3,
        ge=1,
        description="Attempts of a database or HTTP step before its workflow fails.",
    )
    embed_max_attempts: int = Field(
        default=4, ge=1, description="Attempts of the embedding model call."
    )
    embed_retry_interval_seconds: float = Field(
        default=2.0, gt=0, description="Pause between attempts of the embedding call."
    )


class LlmSettings(BaseModel):
    """Model providers for Pydantic AI agents and embeddings."""

    # OpenRouter. Empty key = fall back to the standard OPENROUTER_API_KEY.
    openrouter_api_key: SecretStr = SecretStr("")
    openrouter_model: str = "google/gemini-3.8-flash"
    openrouter_base_url: str = "https://openrouter.ai/api/v1"
    # JEV decision model (`tuttitrip:decide-cloud`), served through OpenRouter.
    jev_model: str = "typesafe/jev-1.13"
    # GB10 (dellpromaxgb10) behind LiteLLM: Qwen (OpenAI-compatible) and the
    # decision models basal and Laya. Empty key = the GB10 models are skipped;
    # the model is left out of its chain.
    gb10_base_url: str = "https://llm.gburek.app/v1"
    gb10_api_key: SecretStr = SecretStr("")
    gb10_agent_model: str = "qwen3.8-27b"
    gb10_chat_model: str = "qwen3.8-27b-chat"
    basal_base_url: str = "https://llm.gburek.app/basal/v1"
    basal_model: str = "basal"
    laya_base_url: str = "https://llm.gburek.app/laya/v1"
    laya_model: str = "laya"
    # Local OpenAI-compatible chat endpoint (SGLang/vLLM/Ollama on the GPU host).
    local_base_url: str = "http://localhost:30000/v1"
    local_api_key: SecretStr = SecretStr("local")
    local_model: str = "qwen3.8-27b"
    # OpenAI-compatible embeddings endpoint (Ollama with nomic-embed-text).
    embedding_base_url: str = "http://localhost:11434/v1"
    embedding_api_key: SecretStr = SecretStr("ollama")
    embedding_model: str = "nomic-embed-text"
    embedding_dimensions: int = Field(default=768, ge=1, le=16000)


class DemoSettings(BaseModel):
    """Daily reset of the jury's demo account (done by the backend)."""

    # Shared secret of the backend's internal reset endpoint (generated by the
    # backend deploy into both env files). Empty = the run warns and, outside
    # `local`, fails.
    reset_secret: SecretStr = SecretStr("")
    # Empty = the environment's API container (`tuttitrip-api[-<env>]:8000`).
    api_base_url: str = ""
    reset_max_attempts: int = Field(
        default=3, ge=1, description="Attempts of the daily reset call to the backend."
    )
    reset_retry_interval_seconds: float = Field(
        default=60.0, gt=0, description="Pause between attempts of the reset call."
    )


class OsmSettings(BaseModel):
    """Open-data services behind ``fetch_place_candidates`` (their usage policies).

    Overpass: below 10 000 queries a day per instance, so an application uses
    about a hundredth of that, never in parallel, and pauses 30 s after a 429.
    ``overpass_daily_limit`` is counted per environment database; develop and
    main share one IP, so each gets 50 (together the 100 a day). Nominatim: at
    most one request a second.
    """

    nominatim_url: str = "https://nominatim.openstreetmap.org"
    overpass_url: str = "https://overpass-api.de/api/interpreter"
    # Identifies the application to the services (required by both policies).
    user_agent: str = (
        "TuttiTrip/1.0 (+https://github.com/HackYeah-TuttiTripTeam/tuttitrip-worker)"
    )
    # A city is fetched again at most once per this many days.
    refresh_days: int = Field(default=30, ge=1, le=365)
    overpass_daily_limit: int = Field(default=50, ge=1, le=100)


class EnrichSettings(BaseModel):
    """Web research that fills in the OSM places (``fetch_place_candidates``).

    OSM has no prices and often no hours or visit time. A cheap OpenRouter model
    with web search finds them; everything it returns carries a ``source_url``
    that the search really cited and is stored unverified. Capabilities other
    than web search are switches, off unless the model handles them well.
    """

    enabled: bool = Field(
        default=True, description="Research places after the OSM import."
    )
    model: str = Field(
        default="deepseek/deepseek-v4.1-flash",
        description="OpenRouter slug of the research model (tools, JSON output).",
    )
    top_n: int = Field(
        default=20, ge=1, le=200, description="Places researched per city."
    )
    categories: list[str] = Field(
        default=["attraction", "museum", "entertainment", "park", "viewpoint"],
        description="Place categories worth researching, in priority order.",
    )
    ttl_days: int = Field(
        default=60,
        ge=1,
        le=730,
        description="A researched place is not researched again for this long.",
    )
    max_cost_usd: float = Field(
        default=1.5,
        gt=0,
        description="Stop researching a city once its calls cost this much.",
    )
    concurrency: int = Field(
        default=4, ge=1, le=16, description="Places researched in parallel."
    )
    timeout_seconds: float = Field(
        default=90.0, gt=0, description="Longest wait for one place."
    )
    max_searches: int = Field(
        default=2,
        ge=1,
        le=10,
        description="Web searches the model may run for one place.",
    )
    search_context_size: Literal["low", "medium", "high"] = Field(
        default="low",
        description="How much of each search result the model reads (cost).",
    )
    request_limit: int = Field(
        default=6,
        ge=1,
        description="Model requests (tool rounds included) for one place.",
    )
    web_fetch: bool = Field(
        default=False,
        description=(
            "Let the model read pages. OpenRouter has no native fetch, so the worker "
            "fetches them itself (SSRF-protected, https only)."
        ),
    )
    max_fetches: int = Field(
        default=2, ge=1, le=10, description="Page fetches per place."
    )
    fetch_blocked_domains: list[str] = Field(
        default=["facebook.com", "instagram.com", "tripadvisor.com"],
        description="Domains the page fetch refuses.",
    )
    thinking: Literal["", "minimal", "low", "medium", "high"] = Field(
        default="",
        description="Reasoning effort (minimal..high); empty leaves it off.",
    )
    planning: bool = Field(
        default=False, description="Add the harness Planning capability."
    )
    compaction: bool = Field(
        default=False, description="Add the harness SummarizingCompaction capability."
    )


class BenchSettings(BaseModel):
    """Manual LLM benchmark (``python -m tuttitrip_worker.bench``; never in CI)."""

    # The judge that scores answers against the reference. With an Anthropic key
    # it is called on Anthropic's OpenAI-compatible endpoint; without one, on
    # OpenRouter (`anthropic/claude-sonnet-5.5`). Empty key = the standard
    # ANTHROPIC_API_KEY.
    judge_model: str = "claude-sonnet-5-5"
    anthropic_base_url: str = "https://api.anthropic.com/v1/"
    anthropic_api_key: SecretStr = SecretStr("")
    concurrency: int = Field(
        default=2,
        ge=1,
        le=16,
        description="Parallel calls per model (the GB10 serves two at a time).",
    )
    request_timeout_seconds: float = Field(
        default=180.0,
        gt=0,
        description="Longest wait for one example, retries included.",
    )


class PlanningSettings(BaseModel):
    """Options of the planning workflows."""

    justification_batch_size: int = Field(
        default=6,
        ge=1,
        le=50,
        description=(
            "Verdicts per model call in write_justifications; local models are "
            "unreliable with long outputs."
        ),
    )


class LinterSettings(BaseModel):
    """Matching of pasted plan items to the catalog."""

    # Off = only the similarity threshold decides (no decision-model call).
    match_with_model: bool = True


class Settings(BaseSettings):
    """Root settings object for the worker."""

    model_config = SettingsConfigDict(
        env_prefix=ENV_PREFIX,
        env_nested_delimiter=ENV_NESTED_DELIMITER,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    environment: str = LOCAL_ENVIRONMENT
    # Application database as the restricted role `tuttitrip_worker` (on the
    # host); locally the owner role of the backend's compose database.
    worker_database_url: SecretStr = SecretStr(LOCAL_DATABASE_URL)
    # DBOS system database (schema `dbos`, migrated by the backend); empty =
    # the application database above.
    dbos_system_database_url: SecretStr = Field(
        default=SecretStr(""), validation_alias="DBOS_SYSTEM_DATABASE_URL"
    )
    # Constant per environment (`<env>`); the backend enqueues with the same
    # value (`app_version`), so its jobs always match a running worker.
    application_version: str = Field(
        default="local", validation_alias="DBOS__APPVERSION"
    )
    db_pool_size: int = Field(
        default=5,
        ge=1,
        description="Connections kept open to the database.",
    )
    db_max_overflow: int = Field(
        default=5, ge=0, description="Extra connections allowed above the pool size."
    )
    dbos: DbosSettings = Field(default_factory=DbosSettings)
    llm: LlmSettings = Field(default_factory=LlmSettings)
    planning: PlanningSettings = Field(default_factory=PlanningSettings)
    demo: DemoSettings = Field(default_factory=DemoSettings)
    osm: OsmSettings = Field(default_factory=OsmSettings)
    enrich: EnrichSettings = Field(default_factory=EnrichSettings)
    bench: BenchSettings = Field(default_factory=BenchSettings)

    linter: LinterSettings = Field(default_factory=LinterSettings)

    def system_database_url(self) -> str:
        """DBOS system database URL (defaults to the application database).

        Returns:
            The URL DBOS uses for its ``dbos`` schema.
        """
        explicit = self.dbos_system_database_url.get_secret_value()
        return explicit or self.worker_database_url.get_secret_value()


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Load settings once per process.

    Returns:
        The cached worker settings.
    """
    return Settings()
